[package]
name = "slp-server-rust"
version = "2.0.0-rust.alpha.1"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lru = "0.4.3"

log = "0.4.8"
env_logger = "0.6.2"

warp = "0.2"
futures = "0.3.1"
futures-util = "0.3.4"
reqwest = "0.9.19"
tokio = { version = "0.2", features = ["full"] }
serde = "1.0"
serde_json = "1.0"

juniper_codegen = { git = "https://github.com/graphql-rust/juniper", branch = "master" }
juniper = { git = "https://github.com/graphql-rust/juniper", branch = "master" }
juniper_warp = { git = "https://github.com/graphql-rust/juniper", branch = "master", features = ["subscriptions"] }
juniper_subscriptions = { git = "https://github.com/graphql-rust/juniper", branch = "master" }
clap = "2.33.0"
owning_ref = "0.4.1"
